services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: splitwise
      POSTGRES_USER: splitwise
      POSTGRES_PASSWORD: splitwise
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U splitwise"]
      interval: 5s
      timeout: 5s
      retries: 5

  splitwise-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/splitwise
      SPRING_DATASOURCE_USERNAME: splitwise
      SPRING_DATASOURCE_PASSWORD: splitwise
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
